name: Readme CI
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [readme]
  workflow_dispatch:
jobs:
  release:
    name: Update README
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update summary & API
        uses: AnandChowdhary/notes-summary@HEAD
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          openAiApiKey: "${{ secrets.OPENAI_API_KEY }}"
          commitMessage: ":pencil: Update themes summary [skip ci]"
          directory: "themes"
      - name: Dispatch AnandChowdhary/everything update
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          repo: AnandChowdhary/everything
          workflow: api.yml
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
